# Generated by Django 4.0.2 on 2022-02-18 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customervehicles_kind'),
        ('operational', '0002_alter_parkmovement_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkmovement',
            name='vehicle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customervehicles'),
        ),
        migrations.AlterField(
            model_name='parkmovement',
            name='entry_date',
            field=models.DateTimeField(),
        ),
    ]
