# Generated by Django 4.0.2 on 2022-02-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational', '0003_parkmovement_vehicle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkmovement',
            name='entry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='parkmovement',
            name='exit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='parkmovement',
            name='validate_date',
            field=models.DateTimeField(null=True),
        ),
    ]
