# Generated by Django 4.0.2 on 2022-02-21 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customervehicles_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customervehicles',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer'),
        ),
    ]
